version: '2'
services:

  api:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: desafio_linx_api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: mongo
    container_name: 'desafio_linx_db'
    volumes:
      - ./docker/volumes/mongodb:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
