name: continuous-integration

on:
  pull_request:
    branches:
      - development
      - staging
      - production
    types:
      - opened
      - reopened
      - synchronize

jobs:

  build:
    uses: alef-carvalho/infra/.github/workflows/ci-build.yml@main

  test:
    uses: alef-carvalho/infra/.github/workflows/ci-test.yml@main
    needs:
      - build

  security:
    uses: alef-carvalho/infra/.github/workflows/ci-security.yml@main
    needs:
      - test

  quality:
    uses: alef-carvalho/infra/.github/workflows/ci-quality.yml@main
    with:
      SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    needs:
      - test
      - security
